R/screenIsotopeData.R, R/trophicDensityPlot.R
=> trophicDensityPlot added

R/compareTwoDistributions.R, R/trophicDensityPlot.R, man/trophicDensityPlot.Rd
trophicDensityPlot and compareTwoDistributions
=> trophicDensityPlot and compareTwoDistributions

R/compareTwoDistributions.R, R/jagsTwoBaselinesFull.R, R/screenIsotopeData.R, R/trophicDensityPlot.R, man/compareTwoDistributions.Rd, man/screenIsotopeData.Rd, vignettes/Orestias.R
compareTwoDistributions
screenIsotopeData
trophicDensityPlot
=> fixed some minor errors

DESCRIPTION, man/TPmodel.Rd, man/generateTPData.Rd, man/jagsTwoBaselines.Rd, man/jagsTwoBaselinesFull.Rd, man/screenIsotopeData.Rd, man/screenIsotopeData1source.Rd, man/screenIsotopeData3sources.Rd, man/screenIsotopeDataMoreSources.Rd, man/toStacked.Rd
=> documentation of beta-testing release

R/TEF.R
McCutchan's values for whole organism vs muscle tissue (d15N)
=> Changed error on TEF

DESCRIPTION, R/TPmodel.R, R/biPlot.R, R/screenIsotopeData.R, R/screenIsotopeDataMoreSources.R, R/theme0.R, R/toStacked.R, README.md
=> added species label to screenIsotopeData

DESCRIPTION
screenIsotopeData now accepts species label
=> version 0.4.0.1000

DESCRIPTION, README.md
Modified description and readme
=> Modified description and readme

R/extractIsotopeData.R, R/multiSpeciesTP.R
Fiche species_community <- species in extractIsotopeData
Changed 1:length to seq_along in multiSpeciesTP
=> minor bugs

DESCRIPTION, README.md
Changed description and readme
=> Changed description and readme

DESCRIPTION, R/parametricTP.R, R/summary.isotopeData.R, README.md
Small changes, decimals rounded in summary and parametricTP
=> Decimals rounded in summary

man/summary.isotopeData.Rd
Lazy-load database corrupt? (Documented, cleaned and rebuilt)
=> Lazy-load database corrupt?

R/extractIsotopeData.R
Default from McCutchan’s assumptions to Post’s assumptions (TDF)
=> Changed extractIsotopeData

R/multiModelTP.R, R/multiSpeciesTP.R
Adaptive, actual iterations and burnin changed to 20,000
Added quiet = false
=> Small changes to multiModelTP and multiSpeciesTP

R/TPmodel.R
=> Small edits to TPmodel

man/TPmodel.Rd
=> Small edits

DESCRIPTION, cran-comments.md
=> cran-comments and DESCRIPTION

DESCRIPTION, README.md
=> Version 0.7.0

DESCRIPTION
=> Changed DESCRIPTION

R/loadIsotopeData.R
Fixed by adding an else case, when loading only one species without
communities to iterate from
=> #71 Error in loadIsotopeData()

README.md
=> Modified readme (news)

DESCRIPTION, README.md
=> Readme and description

DESCRIPTION, R/compareTwoDistributions.R, README.md
Removed dispRity dependence
Improved readme
Added examples in wiki
=> CRAN checks

DESCRIPTION
=> description

R/Finnish_Lakes.R, R/jagsOneBaseline.R, R/multiSpeciesTP.R
minor details in documentation
=> minor details in documentation

.Rbuildignore, .travis.yml
=> Added Travis CI

DESCRIPTION, R/plotTP.R, man/screenFoodWeb.Rd, man/summariseIsotopeData.Rd
Removed the wrapper of SIBER::siberDensityPlot, but included as a
function from the package (to avoid a Travis CI error on building)
=> Removed the wrapper of SIBER::siberDensityPlot

.travis.yml, tests/testthat/test.jagsOneBaseline.R
covr::codecov() and test.jagsOneBaseline tests
=> covr::codecov() and test.jagsOneBaseline tests

tests/testthat/test-jagsOneBaseline.R, tests/testthat/test.jagsOneBaseline.R
Tests for jagsOneBaseline (classes)
=> Tests for jagsOneBaseline (classes)

R/jagsTwoBaselines.R, R/jagsTwoBaselinesFull.R, tests/testthat/test.jagsOneBaseline.R, tests/testthat/test.jagsTwoBaselines.R, tests/testthat/test.jagsTwoBaselinesFull.R
One, two and two baselines full
=> Added tests for classes of jags bayesian models

tests/testthat/test.parametricTP.R, tests/testthat/test.simulateTDF.R
Added tests for simulateTDF and parametricTP
=> Added tests for simulateTDF and parametricTP

R/checkNames.R, R/compareTwoDistributions.R, R/getPosteriorMode.R, R/parametricTP.R, R/plot.isotopeData.R
<- instead of =
lapply instead of sapply
=> Miscellaneous auto::check() errors

R/credibilityIntervals.R, R/posteriorTP.R, R/screenFoodWeb.R
Miscellaneous auto:check() checks
=> Miscellaneous auto:check() checks

R/TDF.R, R/biPlot.R, R/extractIsotopeData.R, R/loadIsotopeData.R, R/multiModelTP.R
Miscellaneous update (auto::check())
=> Miscellaneous update (auto::check())

DESCRIPTION, man/extractIsotopeData.Rd, vignettes/Short_guide_to_tRophicPosition.Rmd
Removed MCMCvis as requested by CRAN
=> Removed MCMCvis as requested by CRAN

tests/testthat/test.jagsBayesianModel.R
=> Miscellaneous auto::check()

README.md
=> README.md with don updated

NEWS.md, cran-comments.md
=> CRAN comments and NEWS
